### ISSUE TITLE
UMAP

### ISSUE THREAD

**Issue by Yuxin-Cui** [bowang-lab/OCAT#1]
Hi, I was wondering how you plot the umaps after the integration. For example, umap by annoated cell types and batch. Thanks

**Comment by lzhangdc** [comment]
Hi Yuxin-Cui,

Thank you very much for your interest in our OCAT. The UMAP is generated using our OCAT feature (ZW) and coloured by the annotated cell types and batches as the validation of OCAT's clustering and batch-effect correction performance. 

We have updated the UMAP clustering code in [https://github.com/bowang-lab/OCAT/blob/master/vignettes/Integration/README.md#clustering](https://github.com/bowang-lab/OCAT/blob/master/vignettes/Integration/README.md#clustering)

Thank you,
Lin
