### ISSUE TITLE
Ghost Cells and Scanpy Integration

### ISSUE THREAD

**Issue by Sayyam-Shah** [bowang-lab/OCAT#6]
Hello,

Thank you for the amazing tool! I am excited to use this as an alternative to harmony. 

How do you decide on the # of ghost cells and the size of the reduced dimension of the raw gene expression data?

After to integrate it with scanpy, I assume it's not necessary to set it as adata.X but an object similar to X_pca in obsm?

**Comment by ChloeXWang** [comment]
Hi Sayyam,

Thank you for your questions and comments! Typically we recommend dim=50-100. We recommend choosing the number of ghost cells based on the size of the dataset, but typically ranging from 30-120. The performance should be quite robust within this range.

For the scanpy integration, we believe that OCAT embeddings should be packaged in obsm as latent embeddings. If you have any further questions, we are more than happy to connect offline.

**Comment by Sayyam-Shah** [comment]
Thank you for getting back to me! I'm excited to use it on our data.

**Comment by Sayyam-Shah** [comment]
Is it possible to input pre-normalized data rather than having OCAT perform log transformation and normalization? Can I input sctransform normalized data and take advantage of OCAT's data integration?

**Comment by ChloeXWang** [comment]
Yes for sure, feel free to specify input arguments `log_norm=False` and `l2_norm=False` when you call the
[run_OCAT](https://github.com/bowang-lab/OCAT/blob/master/OCAT/sparse_encoding.py) function:
e.g., `ZW = OCAT.run_OCAT(data_list, m_list = [50], dim=30, p=0.3, log_norm=False, l2_norm=False)`

It will skip the log transformation and normalization steps and use the data you inputted directly.

**Comment by Sayyam-Shah** [comment]
Thank you so much!
